# Generated by Django 5.1.2 on 2024-11-04 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the page', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Content of the page')),
                ('user', models.ForeignKey(help_text='User who created the page', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pages_user_id_b0179c_idx'), models.Index(fields=['title'], name='pages_title_766786_idx')],
            },
        ),
    ]
