# Generated by Django 5.1.2 on 2024-11-04 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('tag', 'Tag'), ('friend_request', 'Friend Request'), ('message', 'Message'), ('reaction', 'Reaction'), ('accepted_request', 'Accepted Friend Request'), ('post', 'New Post'), ('update', 'Profile Update')], default='like', help_text='Type of notification', max_length=21)),
                ('text', models.TextField(blank=True, help_text='Additional text for the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read')),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the related object', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('receiver', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User sending the notification', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver'], name='notificatio_receive_61b4e9_idx'), models.Index(fields=['sender', 'receiver'], name='notificatio_sender__49b019_idx')],
            },
        ),
    ]
