services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_network

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data  # Added volume for persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_datalog:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - kafka_network

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
        python /app/manage.py wait_for_db &&
        python /app/manage.py makemigrations --noinput &&
        python /app/manage.py migrate --noinput &&
        python /app/manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    volumes:
      - ./backend:/app
      - ./vol/web:/vol/web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_network
      - kafka_network

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - kafka
    env_file:
      - ./backend/.env
    networks:
      - backend_network
      - kafka_network

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - kafka
    env_file:
      - ./backend/.env
    networks:
      - backend_network
      - kafka_network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python /app/manage.py runworker default --verbosity 2
    volumes:
      - ./backend:/app
      - ./vol/web:/vol/web
    depends_on:
      - db
      - redis
      - kafka
    env_file:
      - ./backend/.env
    networks:
      - backend_network
      - kafka_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-true}
        NODE_OPTIONS: ${NODE_OPTIONS:-"--openssl-legacy-provider"}
        REACT_APP_API_URL: ${REACT_APP_API_URL:-"http://localhost:8000"}
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - frontend_network

volumes:
  postgres_data:
  redis_data:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:

networks:
  backend_network:
  frontend_network:
  kafka_network:
