# Generated by Django 5.1.3 on 2024-11-08 17:19

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_conversation(apps, schema_editor):
    Conversation = apps.get_model('messenger', 'Conversation')
    Message = apps.get_model('messenger', 'Message')

    # Create a default conversation if none exists
    default_conversation, created = Conversation.objects.get_or_create()

    # Set the default conversation for all existing messages that don't have one
    Message.objects.filter(conversation__isnull=True).update(conversation=default_conversation)

class Migration(migrations.Migration):
    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_sender__89e028_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_receive_c45f39_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False, help_text='Indicates if receiver deleted the message'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False, help_text='Indicates if sender deleted the message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(
                help_text='Conversation to which this message belongs',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='messenger.conversation',
                null=True  # Temporarily allow null to handle migration issues smoothly.
            ),
        ),
        migrations.RunPython(set_default_conversation),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(
                to='messenger.conversation',
                help_text='Conversation to which this message belongs',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages'
            ),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='messages_convers_8904b4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'),
        ),
    ]
