# Generated by Django 5.1.2 on 2024-10-28 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, help_text='ID of the user who reacted')),
                ('user_username', models.CharField(default='unknown', help_text='Username of the user who reacted', max_length=150)),
                ('reacted_item_type', models.CharField(default='unknown', help_text='Type of the item reacted to (e.g., Post, Comment)', max_length=100)),
                ('reacted_item_id', models.CharField(default='0', help_text='ID of the item reacted to', max_length=255)),
                ('emoji', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', help_text='Emoji used for the reaction', max_length=10)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'reacted_item_type', 'reacted_item_id', 'emoji')},
            },
        ),
    ]
