# Generated by Django 4.2.14 on 2024-07-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_post_image_alter_post_author_and_more'),
        ('reactions', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.post'),
        ),
    ]
