# Generated by Django 5.1.2 on 2024-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagged_item_type', models.CharField(default='unknown', help_text='Type of the item being tagged (e.g., Post, Comment)', max_length=100)),
                ('tagged_item_id', models.CharField(default='unknown', help_text='ID of the item being tagged', max_length=255)),
                ('tagged_user_id', models.IntegerField(default=0, help_text='ID of the user being tagged')),
                ('tagged_user_username', models.CharField(default='unknown', help_text='Username of the user being tagged', max_length=150)),
                ('tagged_by_id', models.IntegerField(default=0, help_text='ID of the user who tagged')),
                ('tagged_by_username', models.CharField(default='unknown', help_text='Username of the user who performed the tagging', max_length=150)),
            ],
            options={
                'verbose_name': 'Tagged Item',
                'verbose_name_plural': 'Tagged Items',
                'ordering': ['-created_at'],
                'unique_together': {('tagged_item_type', 'tagged_item_id', 'tagged_user_id')},
            },
        ),
    ]
