# Generated by Django 5.1.4 on 2025-01-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='tagged_by',
            field=models.ForeignKey(help_text='User who tagged another user', on_delete=django.db.models.deletion.CASCADE, related_name='tags_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tagged_user',
            field=models.ForeignKey(help_text='User being tagged', on_delete=django.db.models.deletion.CASCADE, related_name='tags_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('content_type', 'object_id', 'tagged_user')},
        ),
    ]
