# Generated by Django 4.2.14 on 2024-09-18 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='tagged_by',
            field=models.ForeignKey(help_text='The user who tagged another user.', on_delete=django.db.models.deletion.CASCADE, related_name='tags_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tagged_user',
            field=models.ForeignKey(help_text='The user who is tagged.', on_delete=django.db.models.deletion.CASCADE, related_name='tags_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('content_type', 'object_id', 'tagged_user')},
        ),
    ]
