# Generated by Django 5.1.2 on 2024-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocker_id', models.IntegerField(default=0)),
                ('blocker_username', models.CharField(default='unknown', max_length=150)),
                ('blocked_id', models.IntegerField(default=0)),
                ('blocked_username', models.CharField(default='unknown', max_length=150)),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'constraints': [models.CheckConstraint(condition=models.Q(('blocker_id', models.F('blocked_id')), _negated=True), name='block_self_check')],
                'unique_together': {('blocker_id', 'blocked_id')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.IntegerField(default=0)),
                ('sender_username', models.CharField(default='unknown', max_length=150)),
                ('receiver_id', models.IntegerField(default=0)),
                ('receiver_username', models.CharField(default='unknown', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Friend Request',
                'verbose_name_plural': 'Friend Requests',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender_id', 'receiver_id'), name='unique_pending_request')],
                'unique_together': {('sender_id', 'receiver_id')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1_id', models.IntegerField(default=0)),
                ('user1_username', models.CharField(default='unknown', max_length=150)),
                ('user2_id', models.IntegerField(default=0)),
                ('user2_username', models.CharField(default='unknown', max_length=150)),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'constraints': [models.CheckConstraint(condition=models.Q(('user1_id__lt', models.F('user2_id'))), name='user1_lt_user2')],
                'unique_together': {('user1_id', 'user2_id')},
            },
        ),
    ]
