# Generated by Django 5.1.2 on 2024-11-04 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, help_text='Text content of the story. Can be short and engaging.', null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='text', help_text='Type of media content for the story', max_length=10)),
                ('media_url', models.URLField(blank=True, help_text='URL of the media associated with the story', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the story is active (visible to others)')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='friends', help_text='Visibility of the story', max_length=10)),
                ('user', models.ForeignKey(help_text='User who created the story', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(blank=True, help_text='Users who have viewed the story', related_name='viewed_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='stories_user_id_6205fe_idx'), models.Index(fields=['created_at'], name='stories_created_c866ff_idx'), models.Index(fields=['visibility'], name='stories_visibil_c3581a_idx')],
            },
        ),
    ]
