# Generated by Django 5.1.4 on 2025-01-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(help_text='User who owns the album', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(help_text='Album to which this photo belongs', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.album'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['user'], name='album_user_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['visibility'], name='album_visibility_idx'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_album_title'),
        ),
    ]
