# Generated by Django 4.2.14 on 2024-07-19 14:37

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to=social.models.recipe_image_file_path),
        ),
    ]
