# Generated by Django 4.2.14 on 2024-07-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
