# Generated by Django 4.2.14 on 2024-07-23 13:01

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='static/default_images/default_recipe.jpeg', null=True, upload_to=social.models.recipe_image_file_path),
        ),
    ]
