# Generated by Django 5.1.3 on 2024-11-27 13:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="User's phone number", max_length=128, null=True, region=None),
        ),
    ]
